export const AVAILABLE_MODULES = [
  { id: 'PROPERTY_MANAGEMENT', label: 'Property Management' },
  { id: 'FACILITY_MANAGEMENT', label: 'Facility Management' },
  { id: 'ASSET_MANAGEMENT', label: 'Asset Management' },
  { id: 'PARKING_MANAGEMENT', label: 'Parking Management' },
  { id: 'VISITOR_MANAGEMENT', label: 'Visitor Management' },
  { id: 'SECURITY_MANAGEMENT', label: 'Security Management' },
  { id: 'BILLING_FINANCE', label: 'Billing & Finance' },
  { id: 'RESIDENT_PORTAL', label: 'Resident Portal' },
  { id: 'TENANT_PORTAL', label: 'Tenant Portal' },
  { id: 'INVENTORY_MANAGEMENT', label: 'Inventory Management' },
  { id: 'VENDOR_MANAGEMENT', label: 'Vendor Management' },
  { id: 'PROCUREMENT', label: 'Procurement' },
  { id: 'WORK_ORDERS', label: 'Work Orders' },
  { id: 'PREVENTIVE_MAINTENANCE', label: 'Preventive Maintenance' },
  { id: 'CORRECTIVE_MAINTENANCE', label: 'Corrective Maintenance' },
  { id: 'HOUSEKEEPING', label: 'Housekeeping' },
  { id: 'COMPLAINT_MANAGEMENT', label: 'Complaint Management' },
  { id: 'HELPDESK', label: 'Helpdesk' },
  { id: 'COMMUNITY_MANAGEMENT', label: 'Community Management' },
  { id: 'DOCUMENT_MANAGEMENT', label: 'Document Management' },
  { id: 'UTILITY_MANAGEMENT', label: 'Utility Management' },
  { id: 'ENERGY_MONITORING', label: 'Energy Monitoring' },
  { id: 'IOT_INTEGRATION', label: 'IoT Integration' },
  { id: 'ACCESS_CONTROL', label: 'Access Control' },
  { id: 'LIFT_MANAGEMENT', label: 'Lift Management' },
  { id: 'CCTV_MANAGEMENT', label: 'CCTV Management' },
  { id: 'INCIDENT_MANAGEMENT', label: 'Incident Management' },
  { id: 'EVENT_BOOKING', label: 'Event Booking' },
  { id: 'FACILITY_BOOKING', label: 'Facility Booking' },
  { id: 'VEHICLE_MANAGEMENT', label: 'Vehicle Management' },
  { id: 'STAFF_MANAGEMENT', label: 'Staff Management' },
  { id: 'HR', label: 'HR' },
  { id: 'REPORTS', label: 'Reports' },
  { id: 'ANALYTICS_DASHBOARD', label: 'Analytics Dashboard' },
];

export const AVAILABLE_CATEGORIES = [
  { id: 'RESIDENTIAL', label: 'Residential' },
  { id: 'COMMERCIAL', label: 'Commercial' },
  { id: 'INDUSTRIAL', label: 'Industrial' },
  { id: 'MIXED_USE', label: 'Mixed Use' },
  { id: 'GATED_COMMUNITY', label: 'Gated Community' },
  { id: 'IT_PARK', label: 'IT Park' },
  { id: 'EDUCATIONAL', label: 'Educational' },
  { id: 'HEALTHCARE', label: 'Healthcare' },
  { id: 'HOSPITALITY', label: 'Hospitality' },
  { id: 'GOVERNMENT', label: 'Government' },
];
